# .github/workflows/test.yaml
name: Test UI

on: push

jobs:
  install-dependencies: # This job is for installing dependencies.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache styled-system
        uses: actions/cache@v3
        id: styled-system_cache
        with:
          path: styled-system
          key: ${{ runner.os }}-${{ hashFiles('styled-system') }}
      - name: Cache node_modules
        uses: actions/cache@v3
        id: node_modules_cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Pre dependencies installation
        if: steps.styled-system_cache.outputs.cache-hit != 'true'
        run: npm run prepare
      - name: Install dependencies
        if: steps.node_modules_cache.outputs.cache-hit != 'true'
        run: npm ci
  check: # This job is for checking the code style and type errors.
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Restore styled-system
        id: styled-system_cache
        uses: actions/cache@v3
        with:
          path: styled-system
          key: ${{ runner.os }}-${{ hashFiles('styled-system') }}
      - name: Restore node_modules
        id: node_modules_cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Run Type Check
        run: npm run check:typecheck # check ts compile error
      - name: Run Lint
        run: npm run check:lint
  build-storybook: # This job is for building Storybook.
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Restore styled-system
        id: styled-system_cache
        uses: actions/cache@v3
        with:
          path: styled-system
          key: ${{ runner.os }}-${{ hashFiles('styled-system') }}
      - name: Restore node_modules
        id: node_modules_cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Cache Storybook
        uses: actions/cache@v3
        id: storybook_cache
        with:
          path: storybook-static
          key: ${{ runner.os }}-${{ github.sha }}
      - name: Build Storybook
        if: steps.storybook_cache.outputs.cache-hit != 'true'
        run: npm run storybook:build --quiet
  test-storybook: # This job is for testing in Storybook.
    needs: build-storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Restore styled-system
        id: styled-system_cache
        uses: actions/cache@v3
        with:
          path: styled-system
          key: ${{ runner.os }}-${{ hashFiles('styled-system') }}
      - name: Restore node_modules
        id: node_modules_cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Restore Storybook
        id: storybook_cache
        uses: actions/cache@v3
        with:
          path: storybook-static
          key: ${{ runner.os }}-${{ github.sha }}
      - name: Install Playwright
        run: npx playwright install --with-deps chromium
      # powered by Jest and Playwright
      # For those without a play function: it verifies whether the story renders without any errors.
      # For those with a play function: it also checks for errors in the play function and that all assertions passed.
      # (Better to do a11y test if it's possible...)
      - name: Run Storybook Tests
        run: npm run storybook:ci
